name: Analyze PowerShell Scripts

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PowerShell
        run: |
          # Install PowerShell
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          # Get a list of all PowerShell script files
          $paths = @('./*.ps1', './*.psm1')

          # Run PSScriptAnalyzer on the specified paths
          $results = Invoke-ScriptAnalyzer -Path $paths -Recurse
          
          if ($results.Count -gt 0) {
              Write-Output "Script analysis found issues:"
              $results | Format-Table | Out-String | Write-Output
              exit 1
          } else {
              Write-Output "No issues found."
          }
          continue-on-error: false
