name: Analyze PowerShell Scripts

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: pwsh/setup-pwsh@v3
        with:
          version: '7.3.1'

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          # Run PSScriptAnalyzer and output results
          $results = Invoke-ScriptAnalyzer -Path ./*.ps1, ./*.psm1 -Recurse
          
          if ($results.Count -gt 0) {
              Write-Output "Script analysis found issues:"
              $results | Format-Table | Out-String | Write-Output
              exit 1
          } else {
              Write-Output "No issues found."
          }
          continue-on-error: false
